// SPDX-FileCopyrightText: 2026 1337 · REL AZEUS · MΔSTERMIND
// SPDX-License-Identifier: Apache-2.0

/**
 * Deterministic diff-size gate (docs/BACKLOG-999.md C4, sourced from docs/
 * SOTA-MAP-llm-software-engineering-2026-08.md's diff-size rule): "ONE small
 * unit" is instruction-tier today — a SOUL rule the agent can silently drift
 * from under pressure — so this makes it MECHANICAL, like typecheck/test/
 * build. A firing whose reviewable diff exceeds {@link
 * DIFF_SIZE_THRESHOLD_LINES} is not a diff an automated pass can honestly
 * claim was byte-reviewed; it belongs in more than one unit.
 *
 * Gates on REVIEW BURDEN, not raw line count (the SOTA rule's own caveat): a
 * path matching {@link isMechanicalDiffPath} — a lockfile regen, a generated
 * test snapshot, a vendored/build artifact — contributes zero to the
 * threshold. Those lines were never going to be byte-reviewed by a human
 * either way, so counting them would punish exactly the safe, bulk-
 * verifiable changes the rule says to exempt.
 */

import type { DiffFileStat } from './ports.js';

/**
 * The changed-lines threshold above which a firing's diff exceeds what an
 * automated pass can honestly claim to have byte-reviewed — 400 is the
 * SOTA-MAP's own "common threshold" (400–500 changed lines). Mirrors the
 * spirit of `MAX_AUTO_MERGE_CHANGED_LINES`
 * (apps/dashboard/src/flight/pr-review.ts) at a tighter cap: that PR-merge
 * guard already assumes a human's eyes will see the diff before it merges;
 * this one gates BEFORE any human sees it at all.
 */
export const DIFF_SIZE_THRESHOLD_LINES = 400;

/**
 * Paths whose changed lines are not review burden — regenerated, binary, or
 * build/vendor output nobody reads line-by-line. Deliberately small and
 * extensible rather than exhaustive: an unlisted mechanical path just falls
 * back to counting toward the threshold, the safe direction to fail in.
 */
const MECHANICAL_PATH_PATTERNS: readonly RegExp[] = [
  // Dependency lockfiles — regenerated by the package manager, not authored.
  /(^|\/)(pnpm-lock\.yaml|package-lock\.json|yarn\.lock|Cargo\.lock|poetry\.lock)$/,
  // Binary/generated visual and font assets — byte-diffed, never line-reviewed.
  /\.(png|jpe?g|gif|ico|webp|woff2?|ttf|eot|pdf)$/i,
  // Test-framework-generated snapshots — regenerated by the tool and checked
  // by the assertion against them, not by a human reading the diff.
  /(^|\/)__snapshots__\//,
  // Playwright writes its screenshot baselines beside the spec, in a
  // `<spec file>-snapshots/` directory. Anchored to that exact shape on
  // purpose: an unanchored `-snapshots/` substring would also exempt a
  // hand-authored `user-snapshots/` module, and silently under-counting is
  // the wrong direction for this module to fail in.
  /(^|\/)[^/]+\.(spec|test)\.[jt]sx?-snapshots\//,
  /\.snap$/,
  // Build/vendor output — never hand-edited.
  /(^|\/)(dist|build|coverage|vendor)\//,
];

/** True when `path` is exempt from the diff-size threshold — see the module
 *  doc for why (SOTA-MAP's "gate on review burden, not raw count"). */
export function isMechanicalDiffPath(path: string): boolean {
  return MECHANICAL_PATH_PATTERNS.some((pattern) => pattern.test(path));
}

/** The diff-size gate's verdict — pure data, no side effects. */
export interface DiffSizeVerdict {
  readonly ok: boolean;
  /** Changed lines counted toward the threshold (mechanical paths excluded). */
  readonly reviewLines: number;
  /** Every changed line, mechanical or not — for an honest total in `details`. */
  readonly totalLines: number;
  readonly threshold: number;
  readonly details: string;
}

/**
 * Sums insertions+deletions across `stats`, excluding mechanical paths, and
 * compares the result to `threshold`. Pure — takes the diff facts, returns a
 * verdict; the caller (`firing.ts`) supplies the facts via `VcsPort.diffNumstat`
 * and decides what to do with a failing verdict (the gate's existing revert
 * path, same as a real typecheck/test/build failure).
 */
export function evaluateDiffSize(
  stats: readonly DiffFileStat[],
  threshold: number = DIFF_SIZE_THRESHOLD_LINES,
): DiffSizeVerdict {
  let reviewLines = 0;
  let totalLines = 0;
  for (const file of stats) {
    const lines = file.insertions + file.deletions;
    totalLines += lines;
    if (!isMechanicalDiffPath(file.path)) reviewLines += lines;
  }
  const ok = reviewLines <= threshold;
  const mechanicalLines = totalLines - reviewLines;
  const mechanicalNote = mechanicalLines > 0 ? ` (+${mechanicalLines} mechanical, exempt)` : '';
  const details = ok
    ? `diff size ok: ${reviewLines} review line(s)${mechanicalNote}`
    : `diff too large to honestly claim as byte-reviewed: ${reviewLines} review line(s) ` +
      `exceeds the ${threshold}-line cap${mechanicalNote} — split into more than one unit`;
  return { ok, reviewLines, totalLines, threshold, details };
}
