// SPDX-FileCopyrightText: 2026 1337 · REL AZEUS · MΔSTERMIND
// SPDX-License-Identifier: Apache-2.0

/**
 * licenses/generate-doc — regenerates docs/THIRD-PARTY-LICENSES.md from the
 * REAL installed dependency tree (`pnpm licenses list --json`), and fails
 * loud if any package carries a license outside the allowlist (MIT, ISC, the
 * BSD family, Apache-2.0, MPL-2.0, CC0-1.0, 0BSD, BlueOak-1.0.0, Python-2.0,
 * CC-BY-4.0 — a dual-license package like "MIT OR Apache" passes if any one
 * alternative is allowed). A hand-maintained license inventory drifts the
 * moment a dependency is added or its license changes; generating it from
 * `pnpm licenses list` — and gating on that same output — keeps the doc
 * trustworthy instead of merely aspirational.
 *
 * `--check` (wired into `pnpm verify` as `ci:license-check`) fails without
 * writing if a package's license is disallowed OR the doc differs from what
 * `pnpm licenses list` currently reports; with no flag it writes the
 * refreshed doc in place (`pnpm licenses:update`).
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = fileURLToPath(new URL('../..', import.meta.url));
const DOC_PATH = join(repoRoot, 'docs', 'THIRD-PARTY-LICENSES.md');

// On win32, npm/pnpm/npx resolve to `.cmd` shims, which `execFileSync` can't
// exec directly (EINVAL) without going through a shell — same fix
// `ci/npx-smoke-test.mjs` uses for the same reason.
const bin = (name) => (process.platform === 'win32' ? `${name}.cmd` : name);
const shellOpts = process.platform === 'win32' ? { shell: true } : {};

const ALLOWED_EXACT = new Set([
  'MIT',
  'MIT-0',
  'ISC',
  'Apache-2.0',
  'MPL-2.0',
  'CC0-1.0',
  '0BSD',
  'BlueOak-1.0.0',
  'Python-2.0',
  'CC-BY-4.0',
]);
const ALLOWED_BSD = /^BSD(-\d-Clause)?$/;

/** Splits a dual/multi-license expression ("(A OR B)", "A OR B") into its
 *  individual terms; a single license returns a one-element array. */
export function licenseTerms(license) {
  return license
    .trim()
    .replace(/^\(|\)$/g, '')
    .split(/\s+OR\s+/i)
    .map((term) => term.trim())
    .filter(Boolean);
}

/** A license is allowed if it — or, for a dual-license expression, at least
 *  one of its alternatives — is on the allowlist. Anything else (a
 *  copyleft-strong family like GPL/AGPL/SSPL, or a license this allowlist has
 *  never seen) fails the same way: it just isn't on the list. */
export function isAllowedLicense(license) {
  if (!license) return false;
  return licenseTerms(license).some((term) => ALLOWED_EXACT.has(term) || ALLOWED_BSD.test(term));
}

/** @typedef {{ name: string, versions: string[], license: string }} LicensedPackage */

/** `pnpm licenses list --json` groups packages by license string; this
 *  flattens that into one row per package (each entry already repeats its
 *  own `license`, so the group key is only a fallback), sorted by name so the
 *  rendered doc — and its diff against what's committed — stays stable.
 *  @param {Record<string, Array<{name: string, versions: string[], license?: string}>>} data
 *  @returns {LicensedPackage[]} */
export function flattenLicenseData(data) {
  const packages = [];
  for (const [licenseKey, entries] of Object.entries(data)) {
    for (const entry of entries) {
      packages.push({
        name: entry.name,
        versions: entry.versions,
        license: entry.license || licenseKey,
      });
    }
  }
  packages.sort((a, b) => a.name.localeCompare(b.name));
  return packages;
}

/** @param {LicensedPackage[]} packages */
export function findDisallowed(packages) {
  return packages.filter((pkg) => !isAllowedLicense(pkg.license));
}

/** @param {LicensedPackage[]} packages */
export function renderDoc(packages) {
  const header = [
    '<!--',
    'SPDX-FileCopyrightText: 2026 1337 · REL AZEUS · MΔSTERMIND',
    'SPDX-License-Identifier: Apache-2.0',
    '-->',
    '',
    '# Third-party licenses',
    '',
    'Every npm package this repository depends on (production and development),',
    'with its declared license — generated by `pnpm licenses:update` from',
    '`pnpm licenses list --json` (this file). AUTOPILOT vendors none of them;',
    'they are installed from the public registry by `pnpm install`. Every',
    'license here is checked against an allowlist (MIT, ISC, the BSD family,',
    'Apache-2.0, MPL-2.0, CC0-1.0, 0BSD, BlueOak-1.0.0, Python-2.0, CC-BY-4.0 —',
    'a dual-license package passes if any one alternative is allowed) by',
    '`pnpm run ci:license-check`, which also fails if this file drifts from',
    'what `pnpm licenses list` currently reports. See [`THANKS.md`](../THANKS.md)',
    'for the humans behind them.',
    '',
    '| package | version(s) | license |',
    '| --- | --- | --- |',
  ];
  const rows = packages.map(
    (pkg) => `| ${pkg.name} | ${pkg.versions.join(', ')} | ${pkg.license} |`,
  );
  const footer = [
    '',
    `${packages.length} packages. No copyleft-strong (GPL/AGPL/SSPL) or unknown licenses` +
      ' — enforced by `pnpm run ci:license-check`.',
    '',
  ];
  return [...header, ...rows, ...footer].join('\n');
}

function loadLicenseData() {
  const out = execFileSync(bin('pnpm'), ['licenses', 'list', '--json'], {
    cwd: repoRoot,
    encoding: 'utf8',
    maxBuffer: 32 * 1024 * 1024,
    ...shellOpts,
  });
  return JSON.parse(out);
}

function main() {
  const check = process.argv.includes('--check');
  const packages = flattenLicenseData(loadLicenseData());
  const disallowed = findDisallowed(packages);

  if (disallowed.length > 0) {
    console.error(
      `license-check FAILED: ${disallowed.length} package(s) carry a disallowed license:`,
    );
    for (const pkg of disallowed) {
      console.error(`  ${pkg.name}@${pkg.versions.join(', ')} — ${pkg.license}`);
    }
    process.exit(1);
  }

  const rendered = renderDoc(packages);

  if (check) {
    const current = readFileSync(DOC_PATH, 'utf8');
    if (rendered !== current) {
      console.error(
        'license-check FAILED: docs/THIRD-PARTY-LICENSES.md is out of date with ' +
          '`pnpm licenses list`. Run `pnpm licenses:update`.',
      );
      process.exit(1);
    }
    console.log(`license-check OK: ${packages.length} package(s), all licenses allowed, doc in sync.`);
    return;
  }

  writeFileSync(DOC_PATH, rendered);
  console.log(`licenses: wrote ${DOC_PATH} (${packages.length} packages, all licenses allowed)`);
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) main();
